JohnnyCheese/TTS_X-Wing2.0

- Global.-1.ttslua
- TTS_xwing/src/ModelDB.ttslua
- Tractor.ttslua
- Tractor.xml
- Unassigned Dial.ttslua
- Unassigned Dial.xml
-Fixed Tractor Beam right rear BR not working
-Added W5 Ships
-Cards that adds action now adds the propper action
-Dial now includes Pivot and Aileron moves for appropriate ships
-included generic bases for future assetbundle overhaul
Still needs to assign propper slots for w4 and w5 ships
> Patch 19 09 15

- DataPad.a4dbbf.ttslua
Added trimming options when spawning a list. And correct handling of misspelled pilot names
> Fix spawning lists with incorrect spelling and trailing "\ "

- DataPad.a4dbbf.ttslua
- Global.-1.ttslua
- Unassigned Dial.ttslua
> Fix skilled bombardier, and grappling struts spawning/cost

- Global.-1.ttslua
Thanks to Erik I Can now do the thing
> Added Fun epicMoveWingmate

- Unassigned Dial.ttslua
- Unassigned Dial.xml
Some small talon roll fixes. Also swapped the menu animations to fade, grow/shrink are growing on me a little so I'm happy with whatever folks prefer but seems like fade might be a little less jarring still. :)
> Small talon roll fixes on dial updates

- Unassigned Dial.xml
> Horizontal template button

- DataPad.a4dbbf.ttslua
- Global.-1.ttslua
- TTS_xwing/src/BehaviourDB.ttslua
This PR covers the start of the AI implementation, as well as some refactoring of some core functions to enable the AI to read the board state without printing the results to screen.
The meat of the changes are in the new AIModule in Global, most specifically the "PerformManeuver" function. There are several helper functions within the AIModule that this calls.
The changes that are the most risky are the refactors. These are to:
- CheckArc, which had has the logic split out to ArcCheck.GetTargetsInRelationToArc. I have tested this extensively and am confident there are no lingering side-effects of the refactor.
- ArcCheck.GetPotentialTargets and ArcCheck.GetBullseyeTargets now take an optional "length" parameter. This extends the range at which the functions return potential targets, as …
> Start of AI implementation

- Global.-1.ttslua
- TTS_xwing/src/BehaviourDB.ttslua
These three commits cover the action selection system, and the necessary actions for the TIE Fighter. It also includes a fix for a bug that prevented obstacle avoidance, sorry!
I've documented each commit with information about the changes in that commit. The bulk of the changes are here: https://github.com/JohnnyCheese/TTS_X-Wing2.0/commit/e966ed5fd163b5634ed8ab11c8cdf9aa6c33f9cd
> Action system, and TIE Fighter actions

- Global.-1.ttslua
- TTS_xwing/src/BehaviourDB.ttslua
This PR includes the full Lambda shuttle action AI, and associated improvements to the AI system to handle the new action types.
The first large change is the ability for condition functions to take arguments. This has allowed some consolidation of functions such as targetWithinRange3 and targetWithinRange1.
Condition functions can now store action targets which can be used by the action descriptions. So far this is only used for the coordinate action.
Tokens can be flipped upon creation, so the reinforce tokens can be spawned by the AI facing either side up.
> Lambda shuttle action AI

- DataPad.a4dbbf.ttslua
The XWS spawner will now spawn obstacles if they're part of the JSON.
> XWS Spawner: Add support for spawning obstacles

- DataPad.a4dbbf.ttslua
> Xi Shuttle Cards

- Tractor.ttslua
have the token auto rotate when asigned to a ship its proper orentation
> Tractor Token Rotation

- Global.-1.ttslua
- TTS_xwing/src/BehaviourDB.ttslua
Rein volunteered to add all of the outstanding ship AIs into the mod, so almost all of the work in this PR is theirs.
I just added the ability to have different AI per faction, as the Z-95 has different behaviour for Rebel and S&V pilots.
> All Rebel, S&V, and First Order AI behaviours

- TTS_xwing/src/BehaviourDB.ttslua
AI updates for Rotate until script can be fixed. Organization of the BehaviourDB file. Fixed some existing actions and wrong sloop movements. Added Aggressor.
> AI updates for Rotate and cleanup

- TTS_xwing/src/BehaviourDB.ttslua
Add TIE/se, TIE/vn, TIE/wi, Upsilon, Xi
> AI FO Ships

- TTS_xwing/src/BehaviourDB.ttslua
Fixed action order, stress/non-stress, action priority, structural cleanup, for all existing AI ships
> AI Action cleanup for all ships

- TTS_xwing/src/BehaviourDB.ttslua
BTL-NR2 Y-Wing, MG-100, Res Transport, Res Transport Pod, RZ-2 A-Wing, Delta-7, Eta-2, LAAT/i, Naboo Royal N-1, Belbullab, Tri-Fighter, HMP, Sith Infiltrator
> AI Resistance, Republic, CIS

- TTS_xwing/src/BehaviourDB.ttslua
Alpha-class Star Wing, TIE Reaper, TIE Striker, K-Wing, Jumpmaster, Quadjumper, Fireball
> AI various unique ships

- TTS_xwing/src/BehaviourDB.ttslua
Adding AI for Rogue-class Starfighter and Clone Z-95 Headhunter
> Rogue & Clone Z-95 AI

- Global.-1.ttslua
- TTS_xwing/src/ArcCheck.ttslua
- TTS_xwing/src/BehaviourDB.ttslua
I've only modified the BehaviorDB for TIE/ln and TIE/Advanced x1.  If we like the approach, I'll update all the ships.
I found 2 small errors and corrected them. I did not create a separate commit.
> Added Strike AI

- Global.ttslua
- TODO.md
- TTS_xwing/src/Game/StarForge.ttslua
- TTS_xwing/src/Game/StarForge/StarForge.ttslua
- TTS_xwing/src/Game/StarForge/StarForgeScriptManager.ttslua
- TTS_xwing/src/Player/Team.ttslua
- TTS_xwing/src/Ship/Initiative/InitiativeBase.ttslua
- TTS_xwing/src/ShipVerification.ttslua
Still a work in progress, but starting to get the Star Forge Scripts working as intended.
> Star Forge scripts starting to work

- Global.ttslua
- TODO.md
- TTS_xwing/src/Device/Remote/TrackingTorpedo.ttslua
- TTS_xwing/src/Game/Mechanic/TurnMarker.ttslua
- TTS_xwing/src/Game/StarForge/StarForge.ttslua
- TTS_xwing/src/Game/StarForge/StarForgeDeduper.ttslua
- TTS_xwing/src/Game/StarForge/StarForgeLayout.ttslua
- TTS_xwing/src/Game/StarForge/StarForgeScriptManager.ttslua
Made sure SF.objects didn't get set to nil. 
Muting SF message on initial load.
Toggling SF to appear sets Epic Layout.
> minor fixes:

- TODO.md
- TTS_xwing/src/Dial/DialManager.lua
- TTS_xwing/src/Dial/UnassignedDial.lua
- TTS_xwing/src/Game/Component/Movement/README.md
- TTS_xwing/src/Game/Component/Spawner/DataPad.lua
- TTS_xwing/src/Game/Component/Template/Bank1.lua
- TTS_xwing/src/Game/Component/Template/Bank2.lua
- TTS_xwing/src/Game/Component/Template/Bank3.lua
- TTS_xwing/src/Game/Component/Template/README.md
- TTS_xwing/src/Game/Component/Template/Straight1.lua
- TTS_xwing/src/Game/Component/Template/Straight2.lua
- TTS_xwing/src/Game/Component/Template/Straight3.lua
- TTS_xwing/src/Game/Component/Template/Straight4.lua
- TTS_xwing/src/Game/Component/Template/Straight5.lua
- TTS_xwing/src/Game/Component/Template/TemplateBase.lua
- TTS_xwing/src/Game/Component/Template/Turn1.lua
- TTS_xwing/src/Game/Component/Template/Turn2.lua
- TTS_xwing/src/Game/Component/Template/Turn3.lua
- TTS_xwing/src/Ship/CompositeBase.lua
- TTS_xwing/src/Token/TargetLock.lua
* I made an attempt at getting the DataPad working again from what might have been a bad merge.
> DataPad merge conflicts

- README.md
- TODO.md
- TTS_xwing/src/Game/HotAC/Setup/TransportFreighter.lua
Tweaks to README.md.
Fixes for clones of Transport Freighter.
> Finalizing v 1.16.0

- TTS_xwing/src/Game/VersionCheck.lua
- TTS_xwing/src/Global.lua
* bump of internal version number
* fix for Unassigned Dials being dropped. The fix ignores the Y-axis using 2D X-Z axes.
> Dial drop fix

- TTS_xwing/src/Device/Remote/WildSpaceObjective.lua
- TTS_xwing/src/Device/Remote/WildSpaceObjective.xml
- TTS_xwing/src/Game/HotAC/Setup/Squadron/FormationTool.lua
* fix for target lock tokens for AI ships programmed by the formation tool
* mobile objectives from wildspace which I will eventually integrate into commandos.
> fix for color tint
